import { AdInfo, Answer, cardInfo, Question } from "../../types";
import { recentActivityHeaderItem, HeaderTag } from "../../types";
import { v4 as uuidv4 } from "uuid";

interface Data {
  cards: cardInfo[];
  recentPosts: recentActivityHeaderItem[];
  tags: HeaderTag[];
  ads: AdInfo[];
  questions: Question[];
  answers: Answer[];
}

export const data: Data = {
  cards: [
    {
      type: "blog",
      postId: "random-post-id",
      title: "An Introduction to Oil Paintings",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [3, 3, 4, 5],
      views: 1086,
      imgSrc: "/img/cardImgs/card-example-1.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
      private: true,
      dateCreated: { seconds: 1617265743, nanoseconds: 265000000 },
      dateUpdated: { seconds: 1617265743, nanoseconds: 265000000 },
      minutesRead: 10,
      totalPages: 3,
      pagesRead: 3,
    },
    {
      type: "poem",
      postId: "random-post-id",
      title: "Trees",
      text: "I think that I shall never see A poem as lovely as a tree. A tree whose hungry mouth is prest Against the earth’s sweet flowing breast; A tree that looks at God all day...",
      rating: [3, 1, 4, 5],
      views: 226,
      publisherAvatar: "/img/cardImgs/card-example-1.svg",
      totalPages: 27,
      pagesRead: 22,
    },
    {
      type: "poem",
      postId: "random-post-id",
      title: "Trees",
      text: "I think that I shall never see A poem as lovely as a tree. A tree whose hungry mouth is prest Against the earth’s sweet flowing breast; A tree that looks at God all day...",
      rating: [3, 1, 4, 5],
      views: 356879,
      private: true,
      dateCreated: { seconds: 1617265743, nanoseconds: 265000000 },
      dateUpdated: { seconds: 1617265743, nanoseconds: 265000000 },
      minutesRead: 5,
      publisherAvatar: "/img/icons/person.svg",
    },
    {
      type: "book",
      postId: "random-post-id",
      title:
        "The Lord of the Rings: The Fellowship of the Ring few few few fwe fwe fwef we fwe",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [5, 5, 4, 5],
      views: 132526453,
      imgSrc: "/img/cardImgs/card-example-2.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      private: false,
      dateCreated: { seconds: 1617265743, nanoseconds: 265000000 },
      dateUpdated: { seconds: 1617265743, nanoseconds: 265000000 },
      isBookmarked: true,
      totalPages: 3,
      pagesRead: 1,
    },
    {
      type: "blog",
      postId: "random-post-id",
      title: "An Introduction to Oil Paintings",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [3, 3, 4, 5],
      views: 86124,
      imgSrc: "/img/cardImgs/card-example-1.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
    },
    {
      type: "blog",
      postId: "random-post-id",
      title: "An Introduction to Oil Paintings",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [3, 3, 4, 5],
      views: 1086,
      imgSrc: "/img/cardImgs/card-example-1.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
      totalPages: 3,
      pagesRead: 3,
    },
    {
      type: "poem",
      postId: "random-post-id",
      title: "Trees",
      text: "I think that I shall never see A poem as lovely as a tree. A tree whose hungry mouth is prest Against the earth’s sweet flowing breast; A tree that looks at God all day...",
      rating: [3, 1, 4, 5],
      views: 226,
      publisherAvatar: "/img/cardImgs/card-example-1.svg",
      totalPages: 27,
      pagesRead: 22,
    },
    {
      type: "poem",
      postId: "random-post-id",
      title: "Trees",
      text: "I think that I shall never see A poem as lovely as a tree. A tree whose hungry mouth is prest Against the earth’s sweet flowing breast; A tree that looks at God all day...",
      rating: [3, 1, 4, 5],
      views: 356879,
      publisherAvatar: "/img/icons/person.svg",
    },
    {
      type: "book",
      postId: "random-post-id",
      title: "The Lord of the Rings: The Fellowship of the Ring",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [5, 5, 4, 5],
      views: 1526453,
      imgSrc: "/img/cardImgs/card-example-2.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
      totalPages: 3,
      pagesRead: 1,
    },
    {
      type: "blog",
      postId: "random-post-id",
      title: "An Introduction to Oil Paintings",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [3, 3, 4, 5],
      views: 86124,
      imgSrc: "/img/cardImgs/card-example-1.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
    },
    {
      type: "blog",
      postId: "random-post-id",
      title: "An Introduction to Oil Paintings",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [3, 3, 4, 5],
      views: 1086,
      imgSrc: "/img/cardImgs/card-example-1.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
      totalPages: 3,
      pagesRead: 3,
    },
    {
      type: "poem",
      postId: "random-post-id",
      title: "Trees",
      text: "I think that I shall never see A poem as lovely as a tree. A tree whose hungry mouth is prest Against the earth’s sweet flowing breast; A tree that looks at God all day...",
      rating: [3, 1, 4, 5],
      views: 226,
      publisherAvatar: "/img/cardImgs/card-example-1.svg",
      totalPages: 27,
      pagesRead: 22,
    },
    {
      type: "poem",
      postId: "random-post-id",
      title: "Trees",
      text: "I think that I shall never see A poem as lovely as a tree. A tree whose hungry mouth is prest Against the earth’s sweet flowing breast; A tree that looks at God all day...",
      rating: [3, 1, 4, 5],
      views: 356879,
      publisherAvatar: "/img/icons/person.svg",
    },
    {
      type: "book",
      postId: "random-post-id",
      title: "The Lord of the Rings: The Fellowship of the Ring",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [5, 5, 4, 5],
      views: 13526453,
      imgSrc: "/img/cardImgs/card-example-2.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
      totalPages: 3,
      pagesRead: 1,
    },
    {
      type: "blog",
      postId: "random-post-id",
      title: "An Introduction to Oil Paintings",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [3, 3, 4, 5],
      views: 86124,
      imgSrc: "/img/cardImgs/card-example-1.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
    },
    {
      type: "blog",
      postId: "random-post-id",
      title: "An Introduction to Oil Paintings",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [3, 3, 4, 5],
      views: 1086,
      imgSrc: "/img/cardImgs/card-example-1.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
      totalPages: 3,
      pagesRead: 3,
    },
    {
      type: "poem",
      postId: "random-post-id",
      title: "Trees",
      text: "I think that I shall never see A poem as lovely as a tree. A tree whose hungry mouth is prest Against the earth’s sweet flowing breast; A tree that looks at God all day...",
      rating: [3, 1, 4, 5],
      views: 226,
      publisherAvatar: "/img/cardImgs/card-example-1.svg",
      totalPages: 27,
      pagesRead: 22,
    },
    {
      type: "poem",
      postId: "random-post-id",
      title: "Trees",
      text: "I think that I shall never see A poem as lovely as a tree. A tree whose hungry mouth is prest Against the earth’s sweet flowing breast; A tree that looks at God all day...",
      rating: [3, 1, 4, 5],
      views: 356879,
      publisherAvatar: "/img/icons/person.svg",
    },
    {
      type: "book",
      postId: "random-post-id",
      title: "The Lord of the Rings: The Fellowship of the Ring",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [5, 5, 4, 5],
      views: 132526453,
      imgSrc: "/img/cardImgs/card-example-2.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
      totalPages: 3,
      pagesRead: 1,
    },
    {
      type: "blog",
      postId: "random-post-id",
      title: "An Introduction to Oil Paintings",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [3, 3, 4, 5],
      views: 86124,
      imgSrc: "/img/cardImgs/card-example-1.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
    },
    {
      type: "poem",
      postId: "random-post-id",
      title: "Trees",
      text: "I think that I shall never see A poem as lovely as a tree. A tree whose hungry mouth is prest Against the earth’s sweet flowing breast; A tree that looks at God all day...",
      rating: [3, 1, 4, 5],
      views: 22059,
      publisherAvatar: "/img/icons/person.svg",
    },
    {
      type: "poem",
      postId: "random-post-id",
      title: "Trees",
      text: "I think that I shall never see A poem as lovely as a tree. A tree whose hungry mouth is prest Against the earth’s sweet flowing breast; A tree that looks at God all day...",
      rating: [3, 1, 4, 5],
      views: 226,
      publisherAvatar: "/img/icons/person.svg",
    },
    {
      type: "blog",
      postId: "random-post-id",
      title: "An Introduction to Oil Paintings",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [3, 3, 4, 5],
      views: 86,
      imgSrc: "/img/cardImgs/card-example-1.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
    },
    {
      type: "blog",
      postId: "random-post-id",
      title: "An Introduction to Oil Paintings",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [3, 3, 4, 5],
      views: 86,
      imgSrc: "/img/cardImgs/card-example-1.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
    },
    {
      type: "poem",
      postId: "random-post-id",
      title: "Trees",
      text: "I think that I shall never see A poem as lovely as a tree. A tree whose hungry mouth is prest Against the earth’s sweet flowing breast; A tree that looks at God all day...",
      rating: [3, 1, 4, 5],
      views: 226,
      publisherAvatar: "/img/icons/person.svg",
    },
    {
      type: "poem",
      postId: "random-post-id",
      title: "Trees",
      text: "I think that I shall never see A poem as lovely as a tree. A tree whose hungry mouth is prest Against the earth’s sweet flowing breast; A tree that looks at God all day...",
      rating: [3, 1, 4, 5],
      views: 226,
      publisherAvatar: "/img/icons/person.svg",
    },
    {
      type: "blog",
      postId: "random-post-id",
      title: "An Introduction to Oil Paintings",
      text: "<p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p><p>Q: Why choose oil paint?</p>",
      rating: [3, 3, 4, 5],
      views: 86,
      imgSrc: "/img/cardImgs/card-example-1.svg",
      publisherAvatar: "/img/userAvatars/user-example.png",
      isBookmarked: true,
    },
  ],

  ads: [
    {
      type: "ad",
      adId: uuidv4(),
      adText: "Share your thoughts. Write your own story.",
      adLink: "/create-story",
    },
    {
      type: "ad",
      adId: uuidv4(),
      adText: "Some Random Text",
      adLink: "https://www.google.com/",
    },
    {
      type: "ad",
      adId: uuidv4(),
      adText: "Some Random Text",
      adLink: "https://www.google.com/",
    },
    {
      type: "ad",
      adId: uuidv4(),
      adText: "Some Random Text",
      adLink: "https://www.google.com/",
    },
    {
      type: "ad",
      adId: uuidv4(),
      adText: "Some Random Text",
      adLink: "https://www.google.com/",
    },
    {
      type: "ad",
      adId: uuidv4(),
      adText: "Some Random Text",
      adLink: "https://www.google.com/",
    },
  ],

  recentPosts: [
    {
      publisherAvatar: "/img/icons/person.svg",
      postId: "random-post-id",
    },
    {
      publisherAvatar: "/img/cardImgs/card-example-1.svg",
      postId: "random-post-id",
    },
    {
      publisherAvatar: "/img/userAvatars/user-example.png",
      postId: "random-post-id",
    },
    {
      publisherAvatar: "/img/icons/person.svg",
      postId: "random-post-id",
    },
    {
      publisherAvatar: "/img/cardImgs/card-example-1.svg",
      postId: "random-post-id",
    },
    {
      publisherAvatar: "/img/userAvatars/user-example.png",
      postId: "random-post-id",
    },
    {
      publisherAvatar: "/img/icons/person.svg",
      postId: "random-post-id",
    },
    {
      publisherAvatar: "/img/cardImgs/card-example-1.svg",
      postId: "random-post-id",
    },
    {
      publisherAvatar: "/img/userAvatars/user-example.png",
      postId: "random-post-id",
    },
  ],

  tags: [
    { tag: "story" },
    { tag: "book" },
    { tag: "blog" },
    { tag: "poem" },
    { tag: "journal" },
  ],

  questions: [
    {
      questionId: "gfrw456fg",
      questionText: "Lorem ipsum dolor sit amet consectetur.",
      hashtags: ["#hashtag", "#hello", "#this-is-a-long-hashtag"],
      likes: 3589,
    },
    {
      questionId: "rand-question-id",
      questionText:
        "Should Ifw give up my studies to work part-time? I want to get into Harvard in 2yrs. Little extra-curricular experience.",
      hashtags: ["#hashtag", "#hello", "#this-is-a-long-hashtag"],
      likes: 1245,
    },
    {
      questionId: "rand-question-id",
      questionText: "Lorem ipsum dolor sit amet.",
      hashtags: ["#hashtag", "#hello", "#this-is-a-long-hashtag"],
      likes: 223,
    },
    {
      questionId: "rand-question-id",
      questionText: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      hashtags: ["#hashtag", "#hello", "#this-is-a-long-hashtag"],
      likes: 15689,
    },

    {
      questionId: "rand-question-id",
      questionText: "Lorem ipsum dolor sit amet consectetur adipisi",
      hashtags: ["#hashtag", "#hello", "#this-is-a-long-hashtag"],
      likes: 15689,
    },

    {
      questionId: "rand-question-id",
      questionText:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime accusantium est veniam.",
      hashtags: ["#hashtag", "#hello", "#this-is-a-long-hashtag"],
      likes: 15689,
    },
    {
      questionId: "rand-question-id",
      questionText:
        "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Mollitia.",
      hashtags: ["#hashtag", "#hello", "#this-is-a-long-hashtag"],
      likes: 15689,
    },
    {
      questionId: "rand-question-id",
      questionText:
        "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Et, delectus?",
      hashtags: ["#hashtag", "#hello", "#this-is-a-long-hashtag"],
      likes: 15689,
    },
    {
      questionId: "rand-question-id",
      questionText:
        "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Omnis, consectetur tenetur.",
      hashtags: ["#hashtag", "#hello", "#this-is-a-long-hashtag"],
      likes: 15689,
    },

    {
      questionId: "rand-question-id",
      questionText:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Praeseerg erge rger greaag eif wheuifh iuwehf uiwehffejwjff weuihf iuweh fuiewh fiuwehui fwehiu fhweiu fheui fewuio jfweoi fiwuhr res gser re m odio eius necessitatibus culpa iure?",
      hashtags: ["#hashtag", "#hello", "#this-is-a-long-hashtag"],
      likes: 15689,
    },
  ],

  answers: [
    {
      answerId: "rand-anwswer-id",
      questionId: "rand-question-id",
      answerText:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae, itaque. Lorem ipsum dolor sit amet.",
    },
    {
      answerId: "rand-anwswer-id",
      questionId: "rand-question-id",
      answerText:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae, itaque. Lorem, ipsum dolor.",
    },
    {
      answerId: "rand-anwswer-id",
      questionId: "rand-question-id",
      answerText:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae, itaque. Lorem ipsum dolor sit amet consectetur adipisicing.",
    },
    {
      answerId: "rand-anwswer-id",
      questionId: "rand-question-id",
      answerText:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae, itaque. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatem, amet.",
    },
    {
      answerId: "rand-anwswer-id",
      questionId: "rand-question-id",
      answerText:
        "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Recusandae, itaque. Lorem, ipsum.",
    },
  ],
};
